print("Hello there, my name is Karson")
print("It was a dark and stormy night.")
print("In her attic bedroom Margaret Murray, wrapped in an old patchwork quilt, sat on the")
print("foot of her bed and watched the trees tossing in the frenzied lashing of the wind")
print("This line was created on PyCharm")