print("Hello there, I am Karson")
print("I am studying Mathematics and Physics at Simpson College")
print("I play football when I am not in school but, oddly enough, I have a fascination with soccer.")
print("I love Math and I want to be an aerospace engineer for NASA.")
print("I have a family of 7 including my pet dog, named Gus.")
